name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-glibc
          - x86_64-apple-darwin

    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Compile and release
      uses: rust-build/rust-build.action@v1.4.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        TOOLCHAIN_VERSION: "1.67.0"
      
    - name: Artifact Upload
      id: create-artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-${{matrix.target}}
        path: |
          target/release/nomgen
          target/release/nomgen.exe
        retention-days: 1

  publish:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: build-x86_64-unknown-linux-glibc
        path: release-artifact/x86_64-unknown-linux-glibc

    - uses: actions/download-artifact@v3
      with:
        name: build-x86_64-apple-darwin
        path: release-artifact/x86_64-apple-darwin

    - uses: actions/download-artifact@v3
      with:
        name: build-x86_64-pc-windows-gnu
        path: release-artifact/x86_64-pc-windows-gnu
      
    - name: Zip release
      id: zip-release
      run: |
        zip -rj nomgen-linux-glibc.zip ./release-artifact/x86_64-unknown-linux-glibc/*
        zip -rj nomgen-macos.zip ./release-artifact/x86_64-apple-darwin/*
        zip -rj nomgen-windows.zip ./release-artifact/x86_64-pc-windows-gnu/*

    - uses: ClementTsang/delete-tag-and-release@v0.3.1
      with:
        delete_release: true
        tag_name: live
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: live

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Live Release
        tag_name: live
        body: Latest build
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          nomgen-linux-glibc.zip
          nomgen-macos.zip
          nomgen-windows.zip
