name: Build

on: [push]

jobs:
  build:
    permissions: write-all

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest

    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - name: Build
      id: build-release
      run: cargo build --release
      
    - name: Artifact Upload
      id: create-artifact
      uses: actions/upload-artifact@v3
      with:
        name: nomgen-${{runner.os}}
        path: target/release/nomgen
        retention-days: 1

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nomgen-Linux
        path: release-artifact/linux-glibc-nomgen
    # - uses: actions/download-artifact@v3
    #   with:
    #     name: nomgen-macos-latest
    #     path: macos-nomgen
    # - uses: actions/download-artifact@v3
    #   with:
    #     name: nomgen-windows-latest
    #     path: windows-nomgen
      
    - name: Zip release
      id: zip-release
      run: echo $PWD ; zip build.zip ./release-artifact/*

    - name: Delete latest release
      id: delete-last-release
      uses: sgpublic/delete-release-action@v1.1
      with:
        release-drop: true
        release-keep-count: -1 # remove all
        pre-release-drop: true
        pre-release-keep-count: -1
        pre-release-drop-tag: true
        draft-drop: true
        draft-drop-count: -1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Live Release
        tag_name: live
        body: Latest build
        draft: true
        prerelease: true
        files: |
          build.zip