name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.67.0
          target: ${{matrix.target}}
          default: true
          override: true
  
    - name: Build
      id: build-release
      run: cargo build --target ${{matrix.target}} --release
      
    - name: Artifact Upload
      id: create-artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-${{matrix.os}}
        path: |
          target/${{matrix.target}}/nomgen
          target/${{matrix.target}}/nomgen.exe
        retention-days: 1

  publish:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: build-ubuntu-latest
        path: release-artifact/ubuntu-latest

    - uses: actions/download-artifact@v3
      with:
        name: build-macos-latest
        path: release-artifact/macos-latest

    - uses: actions/download-artifact@v3
      with:
        name: build-windows-latest
        path: release-artifact/windows-latest
      
    - name: Zip release
      id: zip-release
      run: |
        zip -rj nomgen-linux-glibc.zip ./release-artifact/ubuntu-latest/*
        zip -rj nomgen-macos.zip ./release-artifact/macos-latest/*
        zip -rj nomgen-windows.zip ./release-artifact/windows-latest/*

    - uses: ClementTsang/delete-tag-and-release@v0.3.1
      with:
        delete_release: true
        tag_name: live
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: live

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Live Release
        tag_name: live
        body: Latest build
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          nomgen-linux-glibc.zip
          nomgen-macos.zip
          nomgen-windows.zip
