name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest

    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - name: Build
      id: build-release
      run: cargo build --release
      
    - name: Artifact Upload
      id: create-artifact
      uses: actions/upload-artifact@v3
      with:
        name: nomgen-${{runner.os}}
        path: target/release/nomgen
        retention-days: 1

  publish:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nomgen-Linux
        path: release-artifact/linux-glibc-nomgen

    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2

    # - uses: actions/download-artifact@v3
    #   with:
    #     name: nomgen-macos-latest
    #     path: macos-nomgen
    # - uses: actions/download-artifact@v3
    #   with:
    #     name: nomgen-windows-latest
    #     path: windows-nomgen
      
    - name: Zip release
      id: zip-release
      run: echo $PWD ; zip build.zip ./release-artifact/*

    - uses: ClementTsang/delete-tag-and-release@v0.3.1
      with:
        delete_release: true
        tag_name: live
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: live

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Live Release
        tag_name: live
        body: Latest build
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          build.zip