name: Build

on: [push]

jobs:
  build:
    permissions: write-all

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - name: Build
      id: build-release
      run: cargo build --release
      
    - name: Artifact Upload
      id: create-artifact
      uses: actions/upload-artifact@v3
      with:
        name: nomgen-${{runner.os}}
        path: target/release/nomgen
        retention-days: 1

  publish:
    needs: [build]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nomgen-ubuntu-latest
        path: linux-glibc-nomgen
    - uses: actions/download-artifact@v3
      with:
        name: nomgen-macos-latest
        path: macos-nomgen
    - uses: actions/download-artifact@v3
      with:
        name: nomgen-windows-latest
        path: windows-nomgen

    - name: Delete latest release
      id: delete-last-release
      uses: omarabid-forks/action-delete-latest-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Live Release
        tag_name: live
        body: Latest build
        draft: true
        prerelease: true
        files: |
          linux-glibc-nomgen
          macos-nomgen
          windows-nomgen